import React from 'react'
import Author from '../components'
import { getAuthors } from '../services'
import Image from 'next/image';

const about = ({ authors }) => {
    return (

        <div className='container mx-auto px-10 mb-8'>
            <div className='bg-white shadow-lg rounded-lg p-0 lg:p-8 pb-12 mb-8'>
                <div>
                    <h1 className="mt-4 mb-4 text-xl font-bold">Welcome to The Wandering Coder!</h1>
                    <h3 className="mt-4 mb-4 text-xl">
                        👋 Hello and a big, hearty welcome to all our amazing readers! We&apos;re thrilled you&apos;ve decided to join us on this exciting journey through the worlds of travel, self-improvement, web development, and lifestyle.

                    </h3>

                    <br />
                </div>
                {authors.map((author) =>

                    <div key={author.name}>

                        <div>
                            <Image
                                unoptimized="true"
                                alt={author.name}
                                width={100}
                                height={100}
                                className="align-middle rounded-full userimage"
                                src={author.photo.url}
                            />
                        </div>
                        <h3 className="mt-4 mb-4 text-xl font-bold">{author.name}</h3>
                        <p className="text-ls">{author.bio}</p>
                        <br />
                    </div>
                )}
                <div className="mb-8 bg-gray-200 p-8 text-gray italic text-md mt-8">
                    <h2 className='text-pink-600 font-bold text-3xl mb-3'>🚨 Attention, Readers:</h2>
                    Thank you for visiting The Wandering Coder Blog. Please be advised that this blog is a <b>demo project created by the real developer, Tao 🙂</b>. The content, including all articles, tutorials, and author infromation was generated by Chat GPT, and is not intended for commercial use and should not be considered as professional advice. To see Tao&apos;s real portfolio, please visit: <a href="http://hellotaolin.com" target="_blank" className='text-pink-600 hover:text-indigo-600'>hellotaolin.com</a>. Cheers!


                </div>
            </div>

        </div >


    )
}

export default about

export async function getStaticProps() {
    const authors = (await getAuthors()) || [];

    return {
        props: { authors }
    }

}